name: goBrush
description: goBrush is a plugin that's designed to streamline and simplify your mountain building experience
version: "${version}"
website: "https://www.spigotmc.org/resources/23118/"
main: com.arcaniax.gobrush.GoBrushPlugin
author: Arcaniax
api-version: 1.0.0
depend: [FastAsyncWorldEdit]
